[package]
name = "dof_pfp_static"
edition = "2024.beta"
license = "Cascade DOL 1.0"
authors = ["Cascade Foundation (dos@cascade.foundation)"]

[dependencies]
Codec = { git = "https://github.com/studio-mirai/potatoes-app.git", subdir = "packages/codec", rev = "main" }
DosAttribute = { git = "https://github.com/CascadeFoundation/dos_attribute.git", rev = "main" }
DosBucket = { git = "https://github.com/CascadeFoundation/dos_bucket.git", rev = "main" }
DosCollection = { git = "https://github.com/CascadeFoundation/dos_collection.git", rev = "main" }
DosImage = { git = "https://github.com/CascadeFoundation/dos_image.git", rev = "main" }
DosSilo = { git = "https://github.com/CascadeFoundation/dos_silo.git", rev = "main" }

[addresses]
dof_pfp_static = "0x0"
creator = "0x13a53b10794a7a1182068d00400c105acc578c10423ed1078e8f164412c53a14"