[package]
name = "dof_pfp_static"
edition = "2024.beta"
license = "Cascade DOL 1.0"
authors = ["Cascade Foundation (dos@cascade.foundation)"]

[dependencies]
BlobUtils = { git = "https://github.com/studio-mirai/blob_utils.git", rev = "main" }
DosCollection = { git = "https://github.com/CascadeFoundation/dos_collection.git", rev = "main" }
DosHashGatedBucket = { git = "https://github.com/CascadeFoundation/dos_hash_gated_bucket.git", rev = "main" }
DosRegistry = { git = "https://github.com/CascadeFoundation/dos_registry.git", rev = "main" }
DosStaticPfp = { git = "https://github.com/CascadeFoundation/dos_static_pfp.git", rev = "main" }

[addresses]
dof_pfp_static = "0x0"
creator = "0x13a53b10794a7a1182068d00400c105acc578c10423ed1078e8f164412c53a14"