[package]
name = "DofPfpStatic"
edition = "2024.beta"
license = "Cascade DOL 1.0"
authors = ["Cascade Foundation (dos@cascade.foundation)"]

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet", override = true }
Codec = { git = "https://github.com/sui-potatoes/app.git", subdir = "packages/codec", rev = "main" }
DosAttribute = { git = "https://github.com/CascadeFoundation/dos_attribute.git", rev = "main" }
DosCollection = { git = "https://github.com/CascadeFoundation/dos_collection.git", rev = "main" }
DosImage = { git = "https://github.com/CascadeFoundation/dos_image.git", rev = "main" }
DosSilo = { git = "https://github.com/CascadeFoundation/dos_silo.git", rev = "main" }

[addresses]
prime_machin = "0x0"
creator = "0xde0053243f3226649701a7fe2c3988be11941bf3ff3535f3c8c5bf32fc600220"